# Generated by Django 3.2.7 on 2021-09-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardee',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='awardee',
            name='date',
            field=models.DateField(help_text='Date format: yyyy-mm-dd example 2021-09-23'),
        ),
    ]
