# Generated by Django 3.2.7 on 2021-09-25 02:04

import awards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_auto_20210924_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertBG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ImageField(blank=True, null=True, upload_to=awards.models.background_directory_path)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='awardee',
            old_name='date_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='awardee',
            old_name='date_updated',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='awardtitle',
            old_name='date_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='awardtitle',
            old_name='date_updated',
            new_name='updated',
        ),
        migrations.AlterField(
            model_name='awardee',
            name='date',
            field=models.DateField(help_text='Date format: yyyy-mm-dd example 2021-09-23', verbose_name='date of awarding'),
        ),
    ]
