# Generated by Django 3.2.7 on 2021-09-25 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_auto_20210925_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardee',
            name='background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='awards.certbg'),
        ),
    ]
