# Generated by Django 3.2.7 on 2021-09-28 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0006_auto_20210928_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardee',
            name='logo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='awards.adonlogo'),
        ),
    ]
