# Generated by Django 3.2.7 on 2021-09-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0007_awardee_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardee',
            name='citation',
            field=models.TextField(default='In Recognition of Her Outstanding Performance and Dedicated Service.'),
        ),
    ]
