# Generated by Django 3.2.7 on 2021-09-30 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0008_awardee_citation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awardee',
            name='gender',
        ),
    ]
